name: Test

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  matrix-build:
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu-latest
            label: Linux / x86-64
          - image: ubuntu-24.04-arm
            label: Linux / arm64
          - image: macos-15-intel
            label: macOS / x86-64
          - image: macos-latest
            label: macOS / arm64
          - image: windows-latest
            label: Windows / x86-64

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: './go.mod'

    - name: Test examples
      run: go test -v -gcflags="all=-N -l" ./examples/...

    - name: Unit tests
      run: go test -v -gcflags="all=-N -l" -coverprofile coverage.out .

    - name: Upload coverage reports to Codecov
      if: ${{ matrix.image == 'ubuntu-latest' && github.ref == 'refs/heads/main' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  win-arm64:
    name: Windows / arm64
    runs-on: windows-11-arm
    steps:
      # Prevent Git from converting LF to CRLF, which can cause test failures on Windows
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          install: mingw-w64-clang-aarch64-gcc-compat mingw-w64-clang-aarch64-go

      - name: Test
        shell: msys2 {0}
        run: |
          go test -v -gcflags="all=-N -l" ./examples/...
          go test -v -gcflags="all=-N -l" -coverprofile coverage.out .

  freebsd-amd64:
    name: FreeBSD / x86-64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg install -y go
          run: |
            go test -v -gcflags="all=-N -l" ./examples/...
            go test -v -gcflags="all=-N -l" -coverprofile coverage.out .

  freebsd-arm64:
    name: FreeBSD / arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test
        uses: vmactions/freebsd-vm@v1
        with:
          arch: aarch64
          usesh: true
          copyback: false
          prepare: |
            pkg install -y go
          run: |
            go test -v -gcflags="all=-N -l" ./examples/...
            go test -v -gcflags="all=-N -l" -coverprofile coverage.out .
